In [1]:
import pandas as pd

In [2]:
# read csv file

df = pd.read_csv("bollywood_data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
# read specific part of data

new_data = pd.read_csv("bollywood_data.csv", usecols=["Actor", "IMDb"], nrows=5)

In [5]:
new_data

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0
2      Aamir Khan   8.4
3   Ranbir Kapoor   5.6
4   Ranveer Singh   7.0

In [6]:
# write csv

df.to_csv("bollywood_output.csv" , index=False)

# Excel File

In [7]:
 df = pd.read_excel("data.xlsx")

In [8]:
df

  Student School  marks
0   Dhruv    LJS     97
1    Jack    PUS     45
2  Denial    RJD     45
3    Rock    BJS     78
4   Roman    RCS     66
5  Lisban    CKP     90
6   khali    WBK     39
7   Muzan    CRS     61

In [9]:
 df = pd.read_excel("data.xlsx" , sheet_name="College_student")

In [10]:
df

  Student College  sem
0  Mahesh     RJD    1
1    Babu    PDEU    5

In [11]:
# Write Excel

# df.to_excel("output.xlsx", index=False)

In [12]:
# Write Excel sheet wise

with pd.ExcelWriter("Final_Excel.xlsx") as writter:
    new_data.to_excel(writter , sheet_name="bollywood" , index=False)
    df.to_excel(writter , sheet_name="college" , index=False)

# JSON file

In [13]:
df = pd.read_json("data.json")

In [14]:
df

   id   product  price
0   1    Laptop   1200
1   2     Mouse     25
2   3  Keyboard     75